coverage(PrizePool): increase coverage percentage
pooltogether/v4-core pull request #128
Opened 2021-09-28 12:22 UTC by kamescg

Added getters for public variables.

@asselstine  Should we update he public access for ticket, prizeStrategy, balance and liquidityCap, so they're only accessible through the `get` functions?

![image](https://user-images.githubusercontent.com/3408362/135086471-d99c30d9-8f5e-43a2-a947-f32fbe94b416.png)

2021-09-29 23:23 UTC, kamescg commented on test/prize-pool/PrizePool.test.ts
> +  let wallet1: SignerWithAddress;
We use wallet1 in all the other tests.

2021-09-29 23:25 UTC, kamescg commented on contracts/prize-pool/PrizePool.sol
> +  function accountedBalance() external override view returns (uint256) {
Wasn't sure which one we wanted to keep.

2021-09-29 23:33 UTC, kamescg commented on contracts/prize-pool/PrizePool.sol
> +  function onERC721Received(address,address,uint256,bytes calldata) public pure override returns (bytes4) {
Chuuu right @PierrickGT - removed public and just call directly.

2021-09-29 23:34 UTC, kamescg commented on contracts/interfaces/IPrizePool.sol
> +  function getAccountedBalance() external view returns (uint256);
Affirmative.

2021-09-30 06:03 UTC, asselstine commented
@kamescg 

> @asselstine Should we update he public access for ticket, prizeStrategy, balance and liquidityCap, so they're only accessible through the get functions?

Yes!

2021-09-30 14:21 UTC, PierrickGT requested changes

2021-09-30 14:21 UTC, PierrickGT commented on contracts/prize-pool/PrizePool.sol
> +  // }
Remove this comment.

2021-09-30 14:21 UTC, PierrickGT commented on contracts/test/PrizePoolHarness.sol
> +  // }
Remove this comment.

2021-09-30 14:21 UTC, PierrickGT commented on test/prize-pool/PrizePool.test.ts
> +    it('should get the curren block.timestamp', async () => {
```suggestion
    it('should get the current block.timestamp', async () => {
```

2021-09-30 14:21 UTC, PierrickGT commented on test/prize-pool/PrizePool.test.ts
> +      it('should return the inteface selector', async () => {
```suggestion
      it('should return the interface selector', async () => {
```

2021-09-30 20:52 UTC, PierrickGT approved these changes

2021-09-30 20:52 UTC, merged