GaugeController: Add Owner and Manager Roles
pooltogether/v4-core pull request #279
Opened 2022-06-01 21:50 UTC by kamescg

2022-06-01 22:17 UTC, PierrickGT requested changes
Looks good to me. Just need to add a couple tests for the manager role and also remove the `/// @TODO: Add Governance/Executive authorization modifier/function.` comments.

2022-06-01 22:17 UTC, PierrickGT commented on test/GaugeController.test.ts
> +        it('should FAIL to execute BECAUSE of unauthorized access', async () => {
We have no tests for `addGauge`?

2022-06-01 22:17 UTC, PierrickGT commented on test/GaugeController.test.ts
> +        it('should FAIL to execute BECAUSE of unauthorized access', async () => {
We should also test that the function can be executed by a manager.

2022-06-01 22:17 UTC, PierrickGT commented on test/GaugeController.test.ts
> +        it('should SUCCEED to SET a new GaugeReward address', async () => {
We should also test that the function can be executed by a manager.

2022-06-02 22:24 UTC, asselstine commented on contracts/GaugeController.sol
> +    function addGauge(address _gauge) public onlyOwner {
external

2022-06-02 22:24 UTC, asselstine commented on contracts/GaugeController.sol
> +    function addGaugeWithScale(address _gauge, uint256 _scale) public onlyOwner {
external

2022-06-02 22:25 UTC, asselstine commented on contracts/GaugeController.sol
> +    function removeGauge(address _gauge) public onlyOwner {
external

2022-06-02 22:31 UTC, merged